<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <ApplicationIcon>logo-strivea.ico</ApplicationIcon>
        <AssemblyName>Strivea</AssemblyName>
        <RootNamespace>Strivea</RootNamespace>
    </PropertyGroup>

</Project>
